### ISSUE TITLE
Swift 4.1

### ISSUE THREAD

**Issue by YuryRadchenko** [tamanyan/SwiftPageMenu#10]
Xcode 9.3, Swift 4.1

import SwiftPageMenu //<- Error: Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /Users/yury/Developer/.../Carthage/Build/iOS/SwiftPageMenu.framework/Modules/SwiftPageMenu.swiftmodule/x86_64.swiftmodule

/Users/yury/Developer/.../ViewController/Common/Tabbars/UnderlinePagerOption.swift:10:8: Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /Users/yury/Developer/.../Carthage/Build/iOS/SwiftPageMenu.framework/Modules/SwiftPageMenu.swiftmodule/x86_64.swiftmodule

$ carthage update --platform iOS
...
*** Building scheme "SwiftPageMenu" in SwiftPageMenu.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/yury/Developer/.../Carthage/Checkouts/SwiftPageMenu/SwiftPageMenu.xcworkspace -scheme SwiftPageMenu -configuration Release -derivedDataPath /Users/yury/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/SwiftPageMenu/1.2.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/zf/qpdrm77s3ss7xcpycw681q4m0000gn/T/SwiftPageMenu SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/yury/Developer/.../Carthage/Checkouts/SwiftPageMenu)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zf/qpdrm77s3ss7xcpycw681q4m0000gn/T/carthage-xcodebuild.MGAZA2.log

**Comment by tamanyan** [comment]
@YuryRadchenko I'm going to deal with it.

**Comment by tamanyan** [comment]
@YuryRadchenko Pls use "swift-4.1" branch

```
github "tamanyan/SwiftPageMenu" "swift-4.1"
```

**Comment by YuryRadchenko** [comment]
It works. Thanks.
