### ISSUE TITLE
How do I display view on the full screen?

### ISSUE THREAD

**Issue by aayoshinori** [tamanyan/SwiftPageMenu#18]
![simulator screen shot - iphone xr - 2018-12-11 at 09 19 16](https://user-images.githubusercontent.com/5269544/49770008-de4cea00-fd25-11e8-9c99-bab79e034135.png)

In the case of iPhoneX etc., white blanks appear at the bottom of the screen. How can I display view on the full screen?

**Comment by tamanyan** [comment]
@aayoshinori Thank you for your reporting. I will fix the problem.

**Comment by tamanyan** [comment]
#19
