### ISSUE TITLE
custom tableview

### ISSUE THREAD

**Issue by SARAVANANVBK** [tamanyan/SwiftPageMenu#20]
hi,

I am new to iOS. i am trying to implement your menuview in my project.  i have a table view in my storyboard. pls tell me how to implement my custom tableview in childview controller.

**Comment by tamanyan** [comment]
@SARAVANANVBK 

Please refer to the following code. I think you can replace `SwiftPageMenuTableView` with your custom tableview.

https://github.com/tamanyan/SwiftPageMenu/blob/master/PageMenuExample/Sources/ChildViewController.swift
