### ISSUE TITLE
[!] Unable to find a specification for `SwiftPageMenu`

### ISSUE THREAD

**Issue by johnlietzke** [tamanyan/SwiftPageMenu#21]
I am getting an error when I try to install the pod.  This is not my first pod and I have several others working in the project.

The error is: [!] Unable to find a specification for 'SwiftPageMenu'

Thanks

**Comment by tamanyan** [comment]
@johnlietzke I will support CocoaPods

**Comment by pushpankq** [comment]
I am also getting this. How can I fix it?

**Comment by tamanyan** [comment]
Use `pod 'Swift_PageMenu'`
