### ISSUE TITLE
Not able to call pageMenuController(_ pageMenuController: PageMenuController, didSelectMenuItem index: Int, direction: PageMenuNavigationDirection)

### ISSUE THREAD

**Issue by sathishchinniah** [tamanyan/SwiftPageMenu#26]
I am using this PageMenuController. And i have on table view on did select method i used notification center to trigger this delegate method.But not able to pass the int value:

 ```
@objc func overAllSelect(notification: NSNotification) {
    if let val = notification.userInfo?["index"] as? Int {
        
        pageMenuController(_pageMenuController: PageMenuController, didSelectMenuItem index: val, direction: PageMenuNavigationDirection)
        }
    }
```

**Comment by tamanyan** [comment]
@sathishchinniah `pageMenuController(_ pageMenuController: PageMenuController, didSelectMenuItem index: Int, direction: PageMenuNavigationDirection)`. It's a callback method. I don't recommend you to call this method.

this method is called when you select the menu item.
