### ISSUE TITLE
View Controller not displayed 

### ISSUE THREAD

**Issue by nessrinehafi** [tamanyan/SwiftPageMenu#27]
i used  this function  from data source to display : 
```
 func viewControllers(forPageMenuController pageMenuController: PageMenuController) -> [UIViewController] {
   let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let controller = storyboard.instantiateViewController(withIdentifier: "HomeViewController")

        return [controller ]
    }

```

but nothing shows up .

**Comment by tamanyan** [comment]
@nessrinehafi Thank you for letting me know. I'm gonna investigate it.

**Comment by tamanyan** [comment]
@nessrinehafi I've added storyboard case https://github.com/tamanyan/SwiftPageMenu/blob/master/PageMenuExample/Sources/StoryboardPageTabMenuViewController.swift
