### ISSUE TITLE
Right to Left Direction

### ISSUE THREAD

**Issue by muradabujamous** [tamanyan/SwiftPageMenu#31]
How i can make the direction from right to left to support arabic

**Comment by tamanyan** [comment]
@muradabujamous Sorry. I'm not familiar with arabic.

**Comment by muradabujamous** [comment]
Hello Dear,

Just i want to make moving transitions from right to left.
Also to make the tabs directions from right to left :)
Can you please help me

**Comment by tamanyan** [comment]
@muradabujamous Okay. I recommend you to start from last page.

```swift
func defaultPageIndex(forPageMenuController pageMenuController: PageMenuController) -> Int {
    // return last index of the page
   return pages.count - 1
}
```

**Comment by muradabujamous** [comment]
Thank You <3
